# Generated by Django 3.2.6 on 2021-08-10 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_date',
            new_name='duedate',
        ),
    ]
