# Generated by Django 3.2.6 on 2021-08-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210810_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='list',
        ),
    ]
