# Generated by Django 3.2.6 on 2021-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
    ]
