# Generated by Django 3.2.6 on 2021-08-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_ordre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='ordre',
        ),
    ]
