# Generated by Django 3.2.6 on 2021-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='Ici les commentaires de ma note', max_length=255),
            preserve_default=False,
        ),
    ]
