# Generated by Django 3.2.6 on 2021-08-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20210828_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='coordx',
            field=models.CharField(blank=True, default='888', max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='coordy',
            field=models.CharField(blank=True, default='366', max_length=255),
        ),
    ]
