# Generated by Django 3.2.6 on 2021-08-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20210828_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='coordx',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='coordy',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
