# Generated by Django 3.2.6 on 2021-09-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20210828_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='duedate',
        ),
    ]
